---
- name: PLAY TO CREATE THE DEMO USER
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: CREATE DEMOUSER
      user:
        name: demouser
        group: wheel

    - name: ENSURE THE PUBLIC KEY IS PRESENT
      authorized_key:
        user: demouser
        key: "{{ lookup( 'file', 'roles/aws-lab/files/aws-key.pub') }}"
